#davaleba 1
fruits = ["ვაშლი", "ბანანი", "ფორთოხალი", "ატამი", "მსხალი"]
print(f"პირველი ელემენტი: {fruits[0]}")
print(f"უკანასკნელი ელემენტი: {fruits[-1]}")


# davaleba 2
numbers = list(range(1, 11))
print(f"პირველი ელემენტი: {numbers[0]}")
print(f"მეხუთე ელემენტი: {numbers[4]}")
print(f"მეათე ელემენტი: {numbers[9]}")


# davaleba 3
animals = ["ძაღლი", "კატა", "სპილო", "ციყვი"]
animals[0] = "ლომი"
print("განახლებული სია:", animals)


# davaleba 4
movies = ["Inception", "Interstellar", "The Dark Knight", "Prestige"]
print("ბოლო ფილმი:", movies[-1])


# davaleba 5
numbers_list = [10, 20, 30, 40, 50, 60]
print("უკანასკნელი ორი ელემენტი:", numbers_list[-2:])